seeder:
  file: ./seeder/seeder.rb
  disabled: false
parsers:
  - page_type: listing
    file: ./parsers/listing.rb
    disabled: false
  - page_type: details
    file: ./parsers/details.rb
    disabled: false
exporters:
  - exporter_name: contracts_json
    exporter_type: json
    collection: contracts
    write_mode: pretty_array
  - exporter_name: contracts_csv
    exporter_type: csv
    collection: contracts
    fields:
      - header: "tender_id"
        path: "tender_id"
      - header: "submission_deadline"
        path: "submission_deadline"
      - header: "bid_opening"
        path: "bid_opening"
      - header: "tender_booklet_price"
        path: "tender_booklet_price"
      - header: "tender_contact_address"
        path: "tender_contact_address"
      - header: "tender_contact_phone"
        path: "tender_contact_phone"